name: CI

on:
  push:
    branches: ["main", "codex/**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозиторію
        uses: actions/checkout@v4

      - name: Налаштувати Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Встановити залежності
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[dev]

      - name: Запустити перевірки Makefile
        run: make ci

      - name: Завантажити звіт покриття
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
          if-no-files-found: error
